spring:
  application:
    name: tlias

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0526'
    url: jdbc:mysql://localhost:3306/tlias

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射开关
    map-underscore-to-camel-case: true
